### ISSUE TITLE
Request for Open-Sourcing the Tool Mentioned in "FIRM RES: Exposing Broken Device-Cloud Access Control in IoT Through Static Firmware Analysis"

### ISSUE THREAD

**Issue by Nicholas-wei** [Nakuro1999/FirmRES#1]
Dear Maintainer,

I hope this message finds you well. I recently came across your published work titled "FIRM RES: Exposing Broken Device-Cloud Access Control in IoT Through Static Firmware Analysis,". Your research has shed new light on the critical security vulnerabilities within IoT device-cloud access controls, and I commend you for your contributions to the field.

I noticed that the tool developed in conjunction with your work is referenced in this repository. Can you open-source your tool? Thanks!

Best regards

**Comment by Nakuro1999** [comment]
Hi, I have uploaded the conceptual code of firmres and provided an example. I am very sorry that we cannot upload the final version of the tool. The version uploaded is an early version of ours, which includes the core algorithm and processing. This version may have some errors in the results, and I hope it can be of some help to you.

**Comment by Nakuro1999** [comment]
> 亲爱的维护者，
> 
> 希望您收到这条消息时一切安好。我最近看到了您发表的论文《FIRM RES：通过静态固件分析揭露物联网中损坏的设备云访问控制》。您的研究为物联网设备云访问控制中的关键安全漏洞提供了新的见解，我赞扬您对该领域的贡献。
> 
> 我注意到与您的工作一起开发的工具在此存储库中被引用。您可以开源您的工具吗？谢谢！
> 
> 此致

Hi, I have uploaded the conceptual code of FirmRES and provided an example. I am very sorry that we cannot upload the final version of the tool. The version uploaded is an early version of ours, which includes the core algorithm and processing. This version may have some errors in the results, and I hope it can be of some help to you.
